import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { connectMongoDB } from "@/services/mongodb";
import AuthProvider from "@/providers/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Evneto - We got all event info all over the world",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  await connectMongoDB();
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Navbar />
          <main className="py-8 container">{children}</main>
        </AuthProvider>
      </body>
    </html>
  );
}
